name: 'Terraform Blue-Green Deployment'
on:
  push:
    branches:
      - main

env:
  TF_ACTION_WORKING_DIR: 'terraform' 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Check Blue Environment
        run: |
          BLUE_STATUS=$(terraform output blue_status)
          echo "Blue environment status: $BLUE_STATUS"

      - name: Check Green Environment
        run: |
          GREEN_STATUS=$(terraform output green_status)
          echo "Green environment status: $GREEN_STATUS"

      - name: Switch to Green
        if: ${{ env.BLUE_STATUS == 'live' }}
        run: |
          terraform apply -var 'traffic=green' -auto-approve

      - name: Switch to Blue
        if: ${{ env.GREEN_STATUS == 'live' }}
        run: |
          terraform apply -var 'traffic=blue' -auto-approve