Parameters:
  SubnetId:
    Type: String
    Default: subnet-09d106520ce5f25e2
  SecurityGroupId:
    Type: String
    Default: sg-0e35c782d0954ef45
  ImageId:
    Type: String
    Default: ami-0453ec754f44f9a4a

Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
      - !Ref SecurityGroupId